[package]
name = "omsi-net"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
ureq.workspace = true
flate2.workspace = true
sha2.workspace = true
ring = "0.17"
tungstenite = { version = "0.30", default-features = false, features = ["handshake", "rustls-tls-webpki-roots"] }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
